
import { Building, FlatType, CommitteeMember, Notice, FundRecord, MaintenanceRecord, PaymentStatus, OccupancyType, Flat, FamilyMember, WingCommittee, Builder, Language, AmenityBooking } from './types';

export const SOCIETY_INFO = {
  name: "Saurashtra Residency",
  location: "Pasodara, Surat – 395013",
  coordinates: { lat: 21.2334861, lng: 72.9421257 }, 
  googleMapsUrl: "https://maps.app.goo.gl/jZdmVoaupJwwmUd37",
  totalBuildings: 24,
  bhk1Count: 6,
  bhk2Count: 18,
  maintenanceAmount: 700,
  penaltyAmount: 100,
  dueDay: 10,
  amenities: [
    { 
      id: 1, 
      name: "Luxury Clubhouse", 
      desc: "Perfect for birthday parties and family gatherings. Accommodates up to 100 guests.", 
      type: 'utility',
      capacity: 100,
      location: "Near Wing A-1",
      image: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=800"
    },
    { 
      id: 2, 
      name: "Central Party Plot", 
      desc: "Large open-air lawn for weddings and grand community festivals.", 
      type: 'garden',
      capacity: 500,
      location: "Central Courtyard",
      image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&q=80&w=800"
    },
    { 
      id: 3, 
      name: "Mini Theatre", 
      desc: "Private 20-seater cinema for residents to enjoy movies with family.", 
      type: 'utility',
      capacity: 20,
      location: "Basement Wing A-12",
      image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&q=80&w=800"
    }
  ],
};

export const FACILITY_BOOKINGS: any[] = [
  { id: 'b1', facilityId: 1, userName: 'Rahul Sharma', unitNumber: 'A-1-101', date: '2026-03-15', startTime: '18:00', endTime: '22:00', purpose: 'Birthday Party', attendees: 40, isPublic: false, status: 'APPROVED' },
  { id: 'b2', facilityId: 2, userName: 'Priya Patel', unitNumber: 'A-5-204', date: '2026-03-20', startTime: '19:00', endTime: '23:00', purpose: 'Pre-wedding Function', attendees: 150, isPublic: true, status: 'PENDING' },
  { id: 'b3', facilityId: 3, userName: 'Amit Kumar', unitNumber: 'A-12-302', date: '2026-03-12', startTime: '20:00', endTime: '23:00', purpose: 'Movie Night', attendees: 15, isPublic: false, status: 'APPROVED' }
];

export const NOTICES: Notice[] = [
  { id: 'n1', title: 'Water Supply Interruption', content: 'Water supply will be interrupted on Thursday from 10 AM to 2 PM due to tank cleaning.', date: '2026-03-10T08:00:00Z', category: 'Urgent' },
  { id: 'n2', title: 'Holi Celebration 2026', content: 'Join us for the grand Holi celebration at the Central Party Plot this Sunday. Colors and snacks will be provided.', date: '2026-03-09T10:30:00Z', category: 'Event' },
  { id: 'n3', title: 'Lift Maintenance Schedule', content: 'Routine maintenance for all lifts in A-1 to A-6 will be carried out next week.', date: '2026-03-08T14:15:00Z', category: 'General' }
];

export const MAINTENANCE_SAMPLES: MaintenanceRecord[] = [
  { id: 'm1', flatId: 'A-1-101', month: 'March', year: 2026, amount: 700, status: PaymentStatus.PAID, occupancyType: OccupancyType.OWNER, paidDate: '2026-03-05' },
  { id: 'm2', flatId: 'A-2-204', month: 'March', year: 2026, amount: 700, status: PaymentStatus.PENDING, occupancyType: OccupancyType.TENANT },
  { id: 'm3', flatId: 'A-5-302', month: 'February', year: 2026, amount: 700, penaltyAmount: 100, status: PaymentStatus.OVERDUE, occupancyType: OccupancyType.OWNER, lastReminderSent: '2026-03-01' },
  { id: 'm4', flatId: 'A-12-401', month: 'March', year: 2026, amount: 700, status: PaymentStatus.PAID, occupancyType: OccupancyType.OWNER, paidDate: '2026-03-02' }
];

export const FUNDS: FundRecord[] = [
  { id: 'f1', title: 'Navratri Mahotsav 2026', date: '2026-09-15', amount: 50000, status: PaymentStatus.PENDING, purpose: 'Festival', totalCollected: 35000, targetAmount: 50000 },
  { id: 'f2', title: 'Ganesh Chaturthi', date: '2025-08-20', amount: 20000, status: PaymentStatus.PAID, purpose: 'Festival', totalCollected: 20000, targetAmount: 20000 },
  { id: 'f3', title: 'Lift Repair Fund', date: '2026-02-10', amount: 150000, status: PaymentStatus.PENDING, purpose: 'Maintenance', totalCollected: 120000, targetAmount: 150000 },
  { id: 'f4', title: 'Security Camera Upgrade', date: '2026-01-05', amount: 80000, status: PaymentStatus.PAID, purpose: 'Security', totalCollected: 80000, targetAmount: 80000 }
];

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    greeting_morning: "Good Morning",
    greeting_afternoon: "Good Afternoon",
    greeting_evening: "Good Evening",
    greeting_night: "Good Night",
    dashboard: "Command Center",
    maintenance: "Maintenance Lab",
    emergency: "Emergency Desk",
    visitors: "Visitor Access",
    assets: "Residential Assets",
    treasury: "Treasury Analytics",
    audit: "Audit Trail",
    funds: "Community Funds",
    notices: "Broadcasts",
    location: "Atlas & Builders",
    leadership: "Leadership",
    residents: "Residents",
    status_active: "Active",
    quick_pay: "Quick Pay",
    day_shift: "Day Shift",
    night_shift: "Night Shift",
    saurashtra: "Saurashtra",
    residency_portal: "Residency Portal",
    welcome: "Welcome",
    back: "Back",
    emergency_contacts: "Emergency Contacts",
    residential_infra: "Residential Infrastructure",
    finance_hub: "Finance Hub",
    society_bulletin: "Society Bulletin",
    special_funds: "Special Funds & Events",
    meet_committee: "Meet Our Committee",
    site_plan: "Site Plan",
    total_units: "Total Units",
    search_wing: "Search wing (A-1 to A-24)...",
    view_wing_mgmt: "View Wing Management",
    pay_now: "Pay Now",
    receipt: "Receipt",
    export: "Export",
    status_paid: "Paid",
    status_pending: "Pending",
    status_overdue: "Overdue",
    unit: "Unit",
    amount: "Amount",
    actions: "Actions",
    profession_engineer: "Software Engineer",
    profession_business: "Textile Business",
    profession_merchant: "Diamond Merchant",
    profession_teacher: "Teacher",
    profession_doctor: "Doctor",
    profession_ca: "Chartered Accountant",
    profession_govt: "Government Official",
    profession_retired: "Retired",
    profession_homemaker: "Homemaker",
    relation_hof: "Head of Family",
    relation_spouse: "Spouse",
    relation_child: "Child",
    relation_parent: "Parent",
    relation_other: "Other",
    visitor_name: "Visitor Name",
    visitor_phone: "Visitor Phone",
    visitor_purpose: "Purpose of Visit",
    visitor_validity: "Pass Validity",
    visitor_generate: "Generate Access Pass",
    visitor_auth: "Authorized Entry",
    visitor_share: "Share Pass",
    visitor_download: "Download",
    wing_committee: "Wing Committee Members",
    floor_map: "Floor Occupancy Map",
    president: "President",
    vp: "Vice President",
    treasurer: "Treasurer",
    secretary: "Secretary",
    fund_starts: "Starts",
    fund_collected: "Collected",
    fund_target: "Target",
    fund_contribute: "Make a contribution",
    fund_how: "How to contribute?",
    meetings: "Meetings",
    meetings_title: "Society Assemblies",
    meetings_desc: "Schedule and coordinate community meetups",
    meeting_confirm: "Confirm Attendance",
    meeting_archive: "Archive Center",
    audit_title: "Activity Audit",
    audit_desc: "Traceability for administrative action",
    audit_search: "Search logs...",
    exp_title: "Society Treasury",
    exp_desc: "Outflow: Cleaning, Security & Utilities",
    exp_log_new: "Log New Payout",
    exp_category: "Filter Categories",
    total_exp: "Total Expenditure",
    active_records: "Active Records",
    awaiting_appr: "Awaiting Approval",
    logout: "Sign Out",
    office_hours: "Office Hours",
    helpline: "Helpline",
    infrastructure: "Infrastructure",
    system_health: "System Health",
    revenue: "Revenue",
    broadcasts: "Society Broadcasts",
    launchpad: "Launchpad",
    sos: "SOS",
    bills: "Bills",
    facilities: "Amenities",
    helpdesk: "Helpdesk",
    book_now: "Book Slot",
    raise_complaint: "Raise Complaint",
    complaint_title: "Issue Title",
    complaint_desc: "Explain the problem",
    status_resolved: "Resolved",
    status_in_progress: "In Progress",
    admin_dashboard: "Admin Dashboard",
    society_overview: "Society Overview",
    systems_running: "All systems are running smoothly. The community ecosystem is healthy.",
    approve_requests: "Approve Requests",
    security_gate: "Security Gate",
    activity_logs: "Activity Logs",
    total_residents: "Total Residents",
    occupancy: "Occupancy",
    pending_issues: "Pending Issues",
    resolve_issues: "Resolve Issues",
    expense_forecast: "Expense Forecast",
    analyzing_data: "Analyzing data...",
    collections: "Collections",
    this_month: "This Month",
    paid: "Paid",
    total_due: "Total Due",
    pending: "Pending",
    recent_issues: "Recent Issues",
    no_pending_issues: "No Pending Issues",
    view_all_issues: "View All Issues",
    account_up_to_date: "Your account is up to date. Thank you!",
    outstanding_bill: "You have an outstanding maintenance bill. Please settle it soon.",
    view_history: "View History",
    new_pass: "New Pass",
    maintenance_due: "Maintenance Due",
    society_average: "Society Average",
    quick_actions: "Quick Actions",
    support: "Support",
    directory: "Directory",
    meeting: "Meeting",
    starts_in: "Starts In",
    no_upcoming_meetings: "No Upcoming Meetings",
    view_calendar: "View Calendar",
    view_all: "View All",
    no_new_notices: "No New Notices",
    book_amenities: "Book Amenities",
    current_ledger: "Current Ledger",
    history: "History",
    search_unit: "Search Unit ID...",
    all: "ALL",
    owner: "OWNER",
    tenant: "TENANT",
    type: "Type",
    period: "Period",
    generate_cycle: "Generate Cycle",
    lock_month: "Lock Month",
    send_reminders: "Send Reminders",
    whatsapp_reminder: "WhatsApp Reminder",
    apply_penalties: "Apply Penalties",
    enable_recurring: "Enable Recurring",
    recurring_active: "Recurring Active",
    view_details: "View Details",
    society_insights: "Society Insights",
    society_notices: "Society Notices",
    due: "Due",
    open: "Open",
    select_payment_method: "Select Payment Method",
    cancel: "Cancel",
    processing: "Processing...",
    payment_failed: "Payment failed",
    payment_success_msg: "Payment Successful! Your record has been updated.",
    payment_init_failed: "Payment initialization failed. Please check your connection.",
    payment_processed_shortly: "Payment processed. Your record will be updated shortly.",
    no_records_found: "No records found matching filters.",
    showing: "Showing",
    units: "units",
    penalty: "Penalty",
    filter_by: "Filter by",
    overdue: "OVERDUE",
    share: "Share",
    fetching_data: "Fetching data...",
    checkout: "Checkout",
    secure_payment: "Secure Payment",
    close_checkout: "Close Checkout",
    total_amount: "Total Amount",
    payment_receipt: "Payment Receipt",
    close_receipt: "Close Receipt",
    receipt_no: "Receipt No",
    date: "Date",
    unit_number: "Unit Number",
    billing_period: "Billing Period",
    base_amount: "Base Amount",
    penalty_charges: "Penalty Charges",
    total_paid: "Total Paid",
    payment_verified: "Payment Verified",
    receipt_footer: "Computer-generated receipt. No physical signature required.",
    print_pdf_aria: "Print Receipt as PDF",
    print_pdf: "Print PDF",
    share_whatsapp_aria: "Share Receipt on WhatsApp",
    ai_dispute_resolution: "AI Dispute Resolution",
    powered_by_gemini: "Powered by Gemini AI",
    close_dispute_help: "Close Dispute Help",
    close_ai_help: "Close AI Help",
    close: "Close",
    contact_committee_email: "Contact Committee via Email",
    contact_committee: "Contact Committee",
    ticket_details: "Ticket Details",
    update_status: "Update Status",
    no_tickets: "No tickets found."
  },
  gu: {
    greeting_morning: "સુપ્રભાત",
    greeting_afternoon: "શુભ બપોર",
    greeting_evening: "શુભ સાંજ",
    greeting_night: "શુભ રાત્રિ",
    dashboard: "કમાન્ડ સેન્ટર",
    maintenance: "મેન્ટેનન્સ લેબ",
    emergency: "ઇમરજન્સી ડેસ્ક",
    visitors: "વિઝિટર એક્સેસ",
    assets: "રહેણાંક સંપત્તિ",
    treasury: "તિજોરી વિશ્લેષણ",
    audit: "ઓડિટ ટ્રેઇલ",
    funds: "કોમ્યુનિટી ફંડ્સ",
    notices: "બ્રોડકાસ્ટ્સ",
    location: "એટલાસ અને બિલ્ડરો",
    leadership: "નેતૃત્વ",
    residents: "રહેવાસીઓ",
    status_active: "સક્રિય",
    quick_pay: "ઝડપી ચુકવણી",
    day_shift: "ડે શિફ્ટ",
    night_shift: "નાઇટ શિફ્ટ",
    saurashtra: "સૌરાષ્ટ્ર",
    residency_portal: "રેસીડેન્સી પોર્ટલ",
    welcome: "સ્વાગત છે",
    back: "પાછા",
    emergency_contacts: "ઇમરજન્સી સંપર્ક",
    residential_infra: "રહેણાંક ઈન્ફ્રાસ્ટ્રક્ચર",
    finance_hub: "નાણાકીય હબ",
    society_bulletin: "સોસાયટી બુલેટિન",
    special_funds: "ખાસ ફંડ અને કાર્યક્રમો",
    meet_committee: "અમારી સમિતિને મળો",
    site_plan: "સાઇટ પ્લાન",
    total_units: "કુલ યુનિટ્સ",
    search_wing: "વિંગ શોધો (A-1 થી A-24)...",
    view_wing_mgmt: "વિંગ મેનેજમેન્ટ જુઓ",
    pay_now: "ચુકવણી કરો",
    receipt: "રસીદ",
    export: "નિકાસ",
    status_paid: "ચૂકવેલ",
    status_pending: "બાકી",
    status_overdue: "બાકી સમય વીતી ગયો",
    unit: "યુનિટ",
    amount: "રકમ",
    actions: "ક્રિયાઓ",
    profession_engineer: "સોફ્ટવેર એન્જિનિયર",
    profession_business: "ટેક્સટાઇલ બિઝનેસ",
    profession_merchant: "હીરાના વેપારી",
    profession_teacher: "શિક્ષક",
    profession_doctor: "ડોક્ટર",
    profession_ca: "ચાર્ટર્ડ એકાઉન્ટન્ટ",
    profession_govt: "સરકારી અધિકારી",
    profession_retired: "નિવૃત્ત",
    profession_homemaker: "ગૃહિણી",
    relation_hof: "પરિવારના વડા",
    relation_spouse: "જીવનસાથી",
    relation_child: "બાળક",
    relation_parent: "માતા-પિતા",
    relation_other: "અન્ય",
    visitor_name: "મુલાકાતીનું નામ",
    visitor_phone: "મુલાકાતીનો ફોન",
    visitor_purpose: "મુલાકાતનો હેતુ",
    visitor_validity: "પાસની માન્યતા",
    visitor_generate: "એક્સેસ પાસ જનરેટ કરો",
    visitor_auth: "અધિકૃત પ્રવેશ",
    visitor_share: "પાસ શેર કરો",
    visitor_download: "ડાઉનલોડ કરો",
    wing_committee: "વિંગ સમિતિના સભ્યો",
    floor_map: "ફ્લોર ઓક્યુપન્સી મેપ",
    president: "પ્રમુખ",
    vp: "ઉપપ્રમુખ",
    treasurer: "ખજાનચી",
    secretary: "મંત્રી",
    fund_starts: "શરૂઆત",
    fund_collected: "એકત્રિત",
    fund_target: "લક્ષ્યાંક",
    fund_contribute: "ફાળો આપો",
    fund_how: "ફાળો કેવી રીતે આપવો?",
    meetings: "મીટિંગ્સ",
    meetings_title: "સોસાયટી મીટિંગ્સ",
    meetings_desc: "કોમ્યુનિટી મીટિંગ્સનું આયોજન",
    meeting_confirm: "હાજરીની પુષ્ટિ કરો",
    meeting_archive: "આર્કાઇવ સેન્ટર",
    audit_title: "એક્ટિવિટી ઓડિટ",
    audit_desc: "વહીવટી કાર્યવાહીની દેખરેખ",
    audit_search: "ઓડિટ શોધો...",
    exp_title: "સોસાયટી તિજોરી",
    exp_desc: "ખર્ચ: સફાઈ, સુરક્ષા અને સુવિધાઓ",
    exp_log_new: "નવો ખર્ચ ઉમેરો",
    exp_category: "શ્રેણીઓ",
    total_exp: "કુલ ખર્ચ",
    active_records: "સક્રિય રેકોર્ડ્સ",
    awaiting_appr: "મંજૂરીની રાહ જોવાઈ રહી છે",
    logout: "સાઇન આઉટ",
    office_hours: "ઓફિસ સમય",
    helpline: "હેલ્પલાઇન",
    infrastructure: "ઈન્ફ્રાસ્ટ્રક્ચર",
    system_health: "સિસ્ટમ હેલ્થ",
    revenue: "આવક",
    broadcasts: "સોસાયટી પ્રસારણ",
    launchpad: "લોન્ચપેડ",
    sos: "એસઓએસ",
    bills: "બિલ",
    profile: "પ્રોફાઇલ",
    facilities: "સુવિધાઓ",
    helpdesk: "હેલ્પડેસ્ક",
    book_now: "બુક કરો",
    raise_complaint: "ફરિયાદ કરો",
    complaint_title: "ફરિયાદનું શીર્ષક",
    complaint_desc: "સમસ્યા સમજાવો",
    status_resolved: "ઉકેલાઈ ગયું",
    status_in_progress: "ચાલુ છે",
    admin_dashboard: "એડમિન ડેશબોર્ડ",
    society_overview: "સોસાયટી વિહંગાવલોકન",
    systems_running: "બધી સિસ્ટમ્સ બરાબર ચાલી રહી છે. સામુદાયિક ઇકોસિસ્ટમ સ્વસ્થ છે.",
    approve_requests: "વિનંતીઓ મંજૂર કરો",
    security_gate: "સુરક્ષા ગેટ",
    activity_logs: "પ્રવૃત્તિ લોગ",
    total_residents: "કુલ રહેવાસીઓ",
    occupancy: "ઓક્યુપન્સી",
    pending_issues: "બાકી સમસ્યાઓ",
    resolve_issues: "સમસ્યાઓ ઉકેલો",
    expense_forecast: "ખર્ચની આગાહી",
    analyzing_data: "ડેટાનું વિશ્લેષણ કરી રહ્યા છીએ...",
    collections: "કલેક્શન",
    this_month: "આ મહિને",
    paid: "ચૂકવેલ",
    total_due: "કુલ બાકી",
    pending: "બાકી",
    recent_issues: "તાજેતરની સમસ્યાઓ",
    no_pending_issues: "કોઈ બાકી સમસ્યાઓ નથી",
    view_all_issues: "બધી સમસ્યાઓ જુઓ",
    account_up_to_date: "તમારું એકાઉન્ટ અપ ટુ ડેટ છે. આભાર!",
    outstanding_bill: "તમારું મેન્ટેનન્સ બિલ બાકી છે. કૃપા કરીને જલ્દી ચૂકવો.",
    view_history: "ઇતિહાસ જુઓ",
    new_pass: "નવો પાસ",
    maintenance_due: "મેન્ટેનન્સ બાકી",
    society_average: "સોસાયટી સરેરાશ",
    quick_actions: "ઝડપી ક્રિયાઓ",
    support: "સપોર્ટ",
    directory: "ડિરેક્ટરી",
    meeting: "મીટિંગ",
    starts_in: "શરૂ થશે",
    no_upcoming_meetings: "કોઈ આગામી મીટિંગ્સ નથી",
    view_calendar: "કેલેન્ડર જુઓ",
    view_all: "બધું જુઓ",
    no_new_notices: "કોઈ નવી નોટિસ નથી",
    book_amenities: "સુવિધાઓ બુક કરો",
    current_ledger: "વર્તમાન ખાતાવહી",
    history: "ઇતિહાસ",
    search_unit: "યુનિટ આઈડી શોધો...",
    all: "બધા",
    owner: "માલિક",
    tenant: "ભાડુઆત",
    type: "પ્રકાર",
    period: "સમયગાળો",
    generate_cycle: "ચક્ર જનરેટ કરો",
    lock_month: "મહિનો લોક કરો",
    send_reminders: "રિમાઇન્ડર મોકલો",
    whatsapp_reminder: "વોટ્સએપ રિમાઇન્ડર",
    apply_penalties: "દંડ લાગુ કરો",
    enable_recurring: "રિકરિંગ ચાલુ કરો",
    recurring_active: "રિકરિંગ સક્રિય",
    view_details: "વિગતો જુઓ",
    society_insights: "સોસાયટી આંતરદૃષ્ટિ",
    society_notices: "સોસાયટી નોટિસ",
    due: "બાકી",
    select_payment_method: "ચુકવણી પદ્ધતિ પસંદ કરો",
    cancel: "રદ કરો",
    processing: "પ્રક્રિયા ચાલુ છે...",
    payment_failed: "ચુકવણી નિષ્ફળ ગઈ",
    payment_success_msg: "ચુકવણી સફળ! તમારો રેકોર્ડ અપડેટ કરવામાં આવ્યો છે.",
    payment_init_failed: "ચુકવણી પ્રારંભ નિષ્ફળ. કૃપા કરીને તમારું કનેક્શન તપાસો.",
    payment_processed_shortly: "ચુકવણી પ્રક્રિયા થઈ ગઈ. તમારો રેકોર્ડ ટૂંક સમયમાં અપડેટ કરવામાં આવશે.",
    no_records_found: "ફિલ્ટર્સ સાથે મેળ ખાતા કોઈ રેકોર્ડ મળ્યા નથી.",
    showing: "દર્શાવે છે",
    units: "યુનિટ્સ",
    penalty: "દંડ",
    filter_by: "દ્વારા ફિલ્ટર કરો",
    overdue: "બાકી",
    share: "શેર કરો",
    fetching_data: "ડેટા મેળવી રહ્યા છીએ...",
    checkout: "ચેકઆઉટ",
    secure_payment: "સુરક્ષિત ચુકવણી",
    close_checkout: "ચેકઆઉટ બંધ કરો",
    total_amount: "કુલ રકમ",
    payment_receipt: "ચુકવણીની રસીદ",
    close_receipt: "રસીદ બંધ કરો",
    receipt_no: "રસીદ નંબર",
    date: "તારીખ",
    unit_number: "યુનિટ નંબર",
    billing_period: "બિલિંગ સમયગાળો",
    base_amount: "મૂળ રકમ",
    penalty_charges: "દંડ શુલ્ક",
    total_paid: "કુલ ચૂકવેલ",
    payment_verified: "ચુકવણીની પુષ્ટિ થઈ",
    receipt_footer: "કમ્પ્યુટર જનરેટેડ રસીદ. કોઈ ભૌતિક સહીની જરૂર નથી.",
    print_pdf_aria: "રસીદ પીડીએફ તરીકે પ્રિન્ટ કરો",
    print_pdf: "પીડીએફ પ્રિન્ટ કરો",
    share_whatsapp_aria: "વોટ્સએપ પર રસીદ શેર કરો",
    ai_dispute_resolution: "AI વિવાદ નિવારણ",
    powered_by_gemini: "Gemini AI દ્વારા સંચાલિત",
    close_dispute_help: "વિવાદ સહાય બંધ કરો",
    close_ai_help: "AI સહાય બંધ કરો",
    close: "બંધ કરો",
    contact_committee_email: "ઇમેઇલ દ્વારા સમિતિનો સંપર્ક કરો",
    contact_committee: "સમિતિનો સંપર્ક કરો",
    ticket_details: "ટિકિટ વિગતો",
    update_status: "સ્થિતિ અપડેટ કરો",
    no_tickets: "કોઈ ટિકિટ મળી નથી."
  },
  hi: {
    greeting_morning: "सुप्रभात",
    greeting_afternoon: "शुभ दोपहर",
    greeting_evening: "शुभ संध्या",
    greeting_night: "शुभ रात्रि",
    dashboard: "कमांड सेंटर",
    maintenance: "रखरखाव लैब",
    emergency: "आपातकालीन डेस्क",
    visitors: "आगंतुक पहुंच",
    assets: "आवासीय संपत्ति",
    treasury: "खजाना विश्लेषण",
    audit: "ऑडिट ट्रेल",
    funds: "सामुदायिक कोष",
    notices: "प्रसारण",
    location: "एटलस और बिल्डर्स",
    leadership: "नेतृत्व",
    residents: "निवासी",
    status_active: "सक्रिय",
    quick_pay: "त्वरित भुगतान",
    day_shift: "दिन की पाली",
    night_shift: "रात की पाली",
    saurashtra: "सौराष्ट्र",
    residency_portal: "रेजीडेंसी पोर्टल",
    welcome: "स्वागत है",
    back: "पीछे",
    emergency_contacts: "आपातकालीन संपर्क",
    residential_infra: "आवासीय बुनियादी ढांचा",
    finance_hub: "वित्त केंद्र",
    society_bulletin: "सोसायटी बुलेटिन",
    special_funds: "विशेष निधि और कार्यक्रम",
    meet_committee: "हमारी समिति से मिलें",
    site_plan: "साइट प्लान",
    total_units: "कुल इकाइयाँ",
    search_wing: "विंग खोजें (A-1 से A-24)...",
    view_wing_mgmt: "विंग प्रबंधन देखें",
    pay_now: "अभी भुगतान करें",
    receipt: "रसीद",
    export: "निर्यात",
    status_paid: "भुगतान किया गया",
    status_pending: "लंबित",
    status_overdue: "अतिदेय",
    unit: "इकाई",
    amount: "रकम",
    actions: "कार्रवाई",
    profession_engineer: "सॉफ्टवेयर इंजीनियर",
    profession_business: "कपड़ा व्यवसाय",
    profession_merchant: "हीरा व्यापारी",
    profession_teacher: "शिक्षक",
    profession_doctor: "डॉक्टर",
    profession_ca: "चार्टर्ड अकाउंटेंट",
    profession_govt: "सरकारी अधिकारी",
    profession_retired: "सेवानिवृत्त",
    profession_homemaker: "गृहिणी",
    relation_hof: "परिवार के मुखिया",
    relation_spouse: "जीवनसाथी",
    relation_child: "बच्चा",
    relation_parent: "माता-पिता",
    relation_other: "अन्य",
    visitor_name: "आगंतुक का नाम",
    visitor_phone: "आगंतुक का फ़ोन",
    visitor_purpose: "यात्रा का उद्देश्य",
    visitor_validity: "पास की वैधता",
    visitor_generate: "एक्सेस पास जेनरेट करें",
    visitor_auth: "अधिकृत प्रवेश",
    visitor_share: "पास साझा करें",
    visitor_download: "डाउनलोड करें",
    wing_committee: "विंग समिति के सदस्य",
    floor_map: "फ्लोर ऑक्यूपेंसी मैप",
    president: "अध्यक्ष",
    vp: "उपाध्यक्ष",
    treasurer: "कोषाध्यक्ष",
    secretary: "सचिव",
    fund_starts: "शुरू होता है",
    fund_collected: "एकत्रित",
    fund_target: "लक्ष्य",
    fund_contribute: "योगदान दें",
    fund_how: "योगदान कैसे करें?",
    meetings: "बैठकें",
    meetings_title: "सोसायटी बैठकें",
    meetings_desc: "सामुदायिक बैठकों का आयोजन",
    meeting_confirm: "उपस्थिति की पुष्टि करें",
    meeting_archive: "पुरालेख केंद्र",
    audit_title: "गतिविधि ऑडिट",
    audit_desc: "प्रशासनिक कार्रवाई की निगरानी",
    audit_search: "ऑडिट खोजें...",
    exp_title: "सोसायटी खजाना",
    exp_desc: "व्यय: सफाई, सुरक्षा और उपयोगिताएँ",
    exp_log_new: "नया भुगतान दर्ज करें",
    exp_category: "श्रेणियाँ",
    total_exp: "कुल व्यय",
    active_records: "सक्रिय रिकॉर्ड",
    awaiting_appr: "अनुमोदन की प्रतीक्षा है",
    logout: "साइन आउट",
    office_hours: "कार्यालय समय",
    helpline: "हेल्पलाइन",
    infrastructure: "बुनियादी ढांचा",
    system_health: "सिस्टम स्वास्थ्य",
    revenue: "राजस्व",
    broadcasts: "सोसायटी प्रसारण",
    launchpad: "लॉन्चपैड",
    sos: "एसओएस",
    bills: "बिल",
    profile: "प्रोफ़ाइल",
    facilities: "सुविधाएं",
    helpdesk: "हेल्पडेस्क",
    book_now: "अभी बुक करें",
    raise_complaint: "शिकायत दर्ज करें",
    complaint_title: "शिकायत का शीर्षक",
    complaint_desc: "समस्या स्पष्ट करें",
    status_resolved: "समाधान हो गया",
    status_in_progress: "प्रगति में",
    admin_dashboard: "एडमिन डैशबोर्ड",
    society_overview: "सोसायटी अवलोकन",
    systems_running: "सभी सिस्टम सुचारू रूप से चल रहे हैं। सामुदायिक पारिस्थितिकी तंत्र स्वस्थ है।",
    approve_requests: "अनुरोध स्वीकृत करें",
    security_gate: "सुरक्षा गेट",
    activity_logs: "गतिविधि लॉग",
    total_residents: "कुल निवासी",
    occupancy: "अधिभोग",
    pending_issues: "लंबित मुद्दे",
    resolve_issues: "मुद्दे हल करें",
    expense_forecast: "व्यय पूर्वानुमान",
    analyzing_data: "डेटा का विश्लेषण हो रहा है...",
    collections: "संग्रह",
    this_month: "इस महीने",
    paid: "भुगतान किया गया",
    total_due: "कुल देय",
    pending: "लंबित",
    recent_issues: "हाल के मुद्दे",
    no_pending_issues: "कोई लंबित मुद्दा नहीं",
    view_all_issues: "सभी मुद्दे देखें",
    account_up_to_date: "आपका खाता अपडेट है। धन्यवाद!",
    outstanding_bill: "आपका रखरखाव बिल बकाया है। कृपया जल्द भुगतान करें।",
    view_history: "इतिहास देखें",
    new_pass: "नया पास",
    maintenance_due: "रखरखाव देय",
    society_average: "सोसायटी औसत",
    quick_actions: "त्वरित कार्रवाई",
    support: "सहायता",
    directory: "निर्देशिका",
    meeting: "बैठक",
    starts_in: "शुरू होता है",
    no_upcoming_meetings: "कोई आगामी बैठक नहीं",
    view_calendar: "कैलेंडर देखें",
    view_all: "सभी देखें",
    no_new_notices: "कोई नई सूचना नहीं",
    book_amenities: "सुविधाएं बुक करें",
    current_ledger: "वर्तमान लेजर",
    history: "इतिहास",
    search_unit: "यूनिट आईडी खोजें...",
    all: "सभी",
    owner: "मालिक",
    tenant: "किरायेदार",
    type: "प्रकार",
    period: "अवधि",
    generate_cycle: "चक्र उत्पन्न करें",
    lock_month: "महीना लॉक करें",
    send_reminders: "अनुस्मारक भेजें",
    whatsapp_reminder: "व्हाट्सएप रिमाइंडर",
    apply_penalties: "जुर्माना लागू करें",
    enable_recurring: "आवर्ती सक्षम करें",
    recurring_active: "आवर्ती सक्रिय",
    view_details: "विवरण देखें",
    society_insights: "सोसायटी अंतर्दृष्टि",
    society_notices: "सोसायटी सूचनाएं",
    due: "देय",
    select_payment_method: "भुगतान विधि चुनें",
    cancel: "रद्द करें",
    processing: "प्रसंस्करण...",
    payment_failed: "भुगतान विफल रहा",
    payment_success_msg: "भुगतान सफल! आपका रिकॉर्ड अपडेट कर दिया गया है।",
    payment_init_failed: "भुगतान प्रारंभ विफल रहा। कृपया अपना कनेक्शन जांचें।",
    payment_processed_shortly: "भुगतान संसाधित हो गया। आपका रिकॉर्ड जल्द ही अपडेट किया जाएगा।",
    no_records_found: "फ़िल्टर से मेल खाने वाले कोई रिकॉर्ड नहीं मिले।",
    showing: "दिखा रहा है",
    units: "यूनिट",
    penalty: "जुर्माना",
    filter_by: "फ़िल्टर करें",
    overdue: "अतिदेय",
    share: "साझा करें",
    fetching_data: "डेटा प्राप्त किया जा रहा है...",
    checkout: "चेकआउट",
    secure_payment: "सुरक्षित भुगतान",
    close_checkout: "चेकआउट बंद करें",
    total_amount: "कुल राशि",
    payment_receipt: "भुगतान रसीद",
    close_receipt: "रसीद बंद करें",
    receipt_no: "रसीद संख्या",
    date: "तारीख",
    unit_number: "यूनिट नंबर",
    billing_period: "बिलिंग अवधि",
    base_amount: "मूल राशि",
    penalty_charges: "जुर्माना शुल्क",
    total_paid: "कुल भुगतान",
    payment_verified: "भुगतान सत्यापित",
    receipt_footer: "कंप्यूटर जनरेटेड रसीद। किसी भौतिक हस्ताक्षर की आवश्यकता नहीं है।",
    print_pdf_aria: "रसीद को पीडीएफ के रूप में प्रिंट करें",
    print_pdf: "पीडीएफ प्रिंट करें",
    share_whatsapp_aria: "व्हाट्सएप पर रसीद साझा करें",
    ai_dispute_resolution: "AI विवाद समाधान",
    powered_by_gemini: "Gemini AI द्वारा संचालित",
    close_dispute_help: "विवाद सहायता बंद करें",
    close_ai_help: "AI सहायता बंद करें",
    close: "बंद करें",
    contact_committee_email: "ईमेल के माध्यम से समिति से संपर्क करें",
    contact_committee: "समिति से संपर्क करें",
    ticket_details: "टिकट विवरण",
    update_status: "स्थिति अपडेट करें",
    no_tickets: "कोई टिकट नहीं मिला।"
  }
};

export const BUILDER_INFO: Builder = {
  name: "Saurashtra Developers Group",
  founded: "1998",
  projects: ["Saurashtra Residency", "Vibrant Heights", "Patel Enclave", "Diamond Hub"],
  vision: "To create sustainable, premium living spaces that empower families in the heart of Gujarat.",
  logo: "https://api.dicebear.com/7.x/initials/svg?seed=SDG&backgroundColor=2563eb",
  phone: "+91 261 222 3333",
  email: "contact@saurashtradevelopers.com"
};

export const BUILDINGS: Building[] = Array.from({ length: 24 }, (_, i) => {
  const name = `A-${i + 1}`;
  const type = i < 6 ? FlatType.BHK1 : FlatType.BHK2;
  return {
    id: `bld-${name}`,
    name: name,
    type: type,
    totalFloors: 5,
    flatsPerFloor: 4,
    hasLift: true,
    parkingSpots: 1,
    flats: [], 
    wingCommittee: {
      president: { id: '', name: 'Unassigned', position: 'President', phone: '', email: '', imageUrl: '' },
      vicePresident: { id: '', name: 'Unassigned', position: 'VP', phone: '', email: '', imageUrl: '' },
      treasurer: { id: '', name: 'Unassigned', position: 'Treasurer', phone: '', email: '', imageUrl: '' }
    }
  };
});

export const UTILITY_SUMMARY = BUILDINGS.map((b, i) => {
  return {
    buildingId: b.id,
    buildingName: b.name,
    liftBill: 0,
    commonBill: 0,
    sharedWaterBill: 0,
    sharedWith: i % 2 === 0 && i + 1 < 24 ? `A-${i + 2}` : (i > 0 ? `A-${i}` : '')
  };
});

export const EXPENSE_CATEGORIES = [
  { id: 'GARBAGE', label: 'Garbage Collection', color: '#10b981', icon: 'Trash' },
  { id: 'BUILDING_CLEANING', label: 'Pochha & Safai', color: '#3b82f6', icon: 'Brush' },
  { id: 'SECURITY', label: 'Gate Security', color: '#f59e0b', icon: 'ShieldCheck' }
];

export const COMMITTEE: CommitteeMember[] = [
  { id: '1', name: 'Rajesh Patel', position: 'president', phone: '+91 98765 43210', email: 'rajesh.p@residency.com', imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh' },
  { id: '2', name: 'Suresh Vaghani', position: 'secretary', phone: '+91 98765 43211', email: 'suresh.v@residency.com', imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Suresh' },
  { id: '3', name: 'Manoj Goti', position: 'treasurer', phone: '+91 98765 43212', email: 'manoj.g@residency.com', imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Manoj' },
];
