
import { Building, FlatType, CommitteeMember, Notice, FundRecord, MaintenanceRecord, PaymentStatus, OccupancyType, Flat, FamilyMember, WingCommittee, Builder, Language, AmenityBooking } from './types';

export const SOCIETY_INFO = {
  name: "Saurashtra Residency",
  location: "Pasodara, Surat – 395013",
  coordinates: { lat: 21.2334861, lng: 72.9421257 }, 
  googleMapsUrl: "https://maps.app.goo.gl/jZdmVoaupJwwmUd37",
  totalBuildings: 24,
  bhk1Count: 6,
  bhk2Count: 18,
  maintenanceAmount: 700,
  penaltyAmount: 100,
  dueDay: 10,
  amenities: [
    { 
      id: 1, 
      name: "Luxury Clubhouse", 
      desc: "Perfect for birthday parties and family gatherings. Accommodates up to 100 guests.", 
      type: 'utility',
      capacity: 100,
      location: "Near Wing A-1",
      image: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=800"
    },
    { 
      id: 2, 
      name: "Central Party Plot", 
      desc: "Large open-air lawn for weddings and grand community festivals.", 
      type: 'garden',
      capacity: 500,
      location: "Central Courtyard",
      image: "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&q=80&w=800"
    },
    { 
      id: 3, 
      name: "Mini Theatre", 
      desc: "Private 20-seater cinema for residents to enjoy movies with family.", 
      type: 'utility',
      capacity: 20,
      location: "Basement Wing A-12",
      image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&q=80&w=800"
    }
  ],
};

export const FACILITY_BOOKINGS: AmenityBooking[] = [];

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    greeting_morning: "Good Morning",
    greeting_afternoon: "Good Afternoon",
    greeting_evening: "Good Evening",
    greeting_night: "Good Night",
    dashboard: "Command Center",
    maintenance: "Maintenance Lab",
    emergency: "Emergency Desk",
    visitors: "Visitor Access",
    assets: "Residential Assets",
    treasury: "Treasury Analytics",
    audit: "Audit Trail",
    funds: "Community Funds",
    notices: "Broadcasts",
    location: "Atlas & Builders",
    leadership: "Leadership",
    residents: "Residents",
    status_active: "Active",
    quick_pay: "Quick Pay",
    day_shift: "Day Shift",
    night_shift: "Night Shift",
    saurashtra: "Saurashtra",
    residency_portal: "Residency Portal",
    welcome: "Welcome",
    back: "Back",
    emergency_contacts: "Emergency Contacts",
    residential_infra: "Residential Infrastructure",
    finance_hub: "Finance Hub",
    society_bulletin: "Society Bulletin",
    special_funds: "Special Funds & Events",
    meet_committee: "Meet Our Committee",
    site_plan: "Site Plan",
    total_units: "Total Units",
    search_wing: "Search wing (A-1 to A-24)...",
    view_wing_mgmt: "View Wing Management",
    pay_now: "Pay Now",
    receipt: "Receipt",
    export: "Export",
    status_paid: "Paid",
    status_pending: "Pending",
    status_overdue: "Overdue",
    unit: "Unit",
    amount: "Amount",
    actions: "Actions",
    profession_engineer: "Software Engineer",
    profession_business: "Textile Business",
    profession_merchant: "Diamond Merchant",
    profession_teacher: "Teacher",
    profession_doctor: "Doctor",
    profession_ca: "Chartered Accountant",
    profession_govt: "Government Official",
    profession_retired: "Retired",
    profession_homemaker: "Homemaker",
    relation_hof: "Head of Family",
    relation_spouse: "Spouse",
    relation_child: "Child",
    relation_parent: "Parent",
    relation_other: "Other",
    visitor_name: "Visitor Name",
    visitor_phone: "Visitor Phone",
    visitor_purpose: "Purpose of Visit",
    visitor_validity: "Pass Validity",
    visitor_generate: "Generate Access Pass",
    visitor_auth: "Authorized Entry",
    visitor_share: "Share Pass",
    visitor_download: "Download",
    wing_committee: "Wing Committee Members",
    floor_map: "Floor Occupancy Map",
    president: "President",
    vp: "Vice President",
    treasurer: "Treasurer",
    secretary: "Secretary",
    fund_starts: "Starts",
    fund_collected: "Collected",
    fund_target: "Target",
    fund_contribute: "Make a contribution",
    fund_how: "How to contribute?",
    meetings: "Meetings",
    meetings_title: "Society Assemblies",
    meetings_desc: "Schedule and coordinate community meetups",
    meeting_confirm: "Confirm Attendance",
    meeting_archive: "Archive Center",
    audit_title: "Activity Audit",
    audit_desc: "Traceability for administrative action",
    audit_search: "Search logs...",
    exp_title: "Society Treasury",
    exp_desc: "Outflow: Cleaning, Security & Utilities",
    exp_log_new: "Log New Payout",
    exp_category: "Filter Categories",
    total_exp: "Total Expenditure",
    active_records: "Active Records",
    awaiting_appr: "Awaiting Approval",
    logout: "Sign Out",
    office_hours: "Office Hours",
    helpline: "Helpline",
    infrastructure: "Infrastructure",
    system_health: "System Health",
    revenue: "Revenue",
    broadcasts: "Society Broadcasts",
    launchpad: "Launchpad",
    sos: "SOS",
    bills: "Bills",
    profile: "Profile",
    facilities: "Amenities",
    helpdesk: "Helpdesk",
    book_now: "Book Slot",
    raise_complaint: "Raise Complaint",
    complaint_title: "Issue Title",
    complaint_desc: "Explain the problem",
    status_resolved: "Resolved",
    status_in_progress: "In Progress"
  },
  gu: {
    greeting_morning: "સુપ્રભાત",
    greeting_afternoon: "શુભ બપોર",
    greeting_evening: "શુભ સાંજ",
    greeting_night: "શુભ રાત્રિ",
    dashboard: "કમાન્ડ સેન્ટર",
    maintenance: "મેન્ટેનન્સ લેબ",
    emergency: "ઇમરજન્સી ડેસ્ક",
    visitors: "વિઝિટર એક્સેસ",
    assets: "રહેણાંક સંપત્તિ",
    treasury: "તિજોરી વિશ્લેષણ",
    audit: "ઓડિટ ટ્રેઇલ",
    funds: "કોમ્યુનિટી ફંડ્સ",
    notices: "બ્રોડકાસ્ટ્સ",
    location: "એટલાસ અને બિલ્ડરો",
    leadership: "નેતૃત્વ",
    residents: "રહેવાસીઓ",
    status_active: "સક્રિય",
    quick_pay: "ઝડપી ચુકવણી",
    day_shift: "ડે શિફ્ટ",
    night_shift: "નાઇટ શિફ્ટ",
    saurashtra: "સૌરાષ્ટ્ર",
    residency_portal: "રેસીડેન્સી પોર્ટલ",
    welcome: "સ્વાગત છે",
    back: "પાછા",
    emergency_contacts: "ઇમરજન્સી સંપર્ક",
    residential_infra: "રહેણાંક ઈન્ફ્રાસ્ટ્રક્ચર",
    finance_hub: "નાણાકીય હબ",
    society_bulletin: "સોસાયટી બુલેટિન",
    special_funds: "ખાસ ફંડ અને કાર્યક્રમો",
    meet_committee: "અમારી સમિતિને મળો",
    site_plan: "સાઇટ પ્લાન",
    total_units: "કુલ યુનિટ્સ",
    search_wing: "વિંગ શોધો (A-1 થી A-24)...",
    view_wing_mgmt: "વિંગ મેનેજમેન્ટ જુઓ",
    pay_now: "ચુકવણી કરો",
    receipt: "રસીદ",
    export: "નિકાસ",
    status_paid: "ચૂકવેલ",
    status_pending: "બાકી",
    status_overdue: "બાકી સમય વીતી ગયો",
    unit: "યુનિટ",
    amount: "રકમ",
    actions: "ક્રિયાઓ",
    profession_engineer: "સોફ્ટવેર એન્જિનિયર",
    profession_business: "ટેક્સટાઇલ બિઝનેસ",
    profession_merchant: "હીરાના વેપારી",
    profession_teacher: "શિક્ષક",
    profession_doctor: "ડોક્ટર",
    profession_ca: "ચાર્ટર્ડ એકાઉન્ટન્ટ",
    profession_govt: "સરકારી અધિકારી",
    profession_retired: "નિવૃત્ત",
    profession_homemaker: "ગૃહિણી",
    relation_hof: "પરિવારના વડા",
    relation_spouse: "જીવનસાથી",
    relation_child: "બાળક",
    relation_parent: "માતા-પિતા",
    relation_other: "અન્ય",
    visitor_name: "મુલાકાતીનું નામ",
    visitor_phone: "મુલાકાતીનો ફોન",
    visitor_purpose: "મુલાકાતનો હેતુ",
    visitor_validity: "પાસની માન્યતા",
    visitor_generate: "એક્સેસ પાસ જનરેટ કરો",
    visitor_auth: "અધિકૃત પ્રવેશ",
    visitor_share: "પાસ શેર કરો",
    visitor_download: "ડાઉનલોડ કરો",
    wing_committee: "વિંગ સમિતિના સભ્યો",
    floor_map: "ફ્લોર ઓક્યુપન્સી મેપ",
    president: "પ્રમુખ",
    vp: "ઉપપ્રમુખ",
    treasurer: "ખજાનચી",
    secretary: "મંત્રી",
    fund_starts: "શરૂઆત",
    fund_collected: "એકત્રિત",
    fund_target: "લક્ષ્યાંક",
    fund_contribute: "ફાળો આપો",
    fund_how: "ફાળો કેવી રીતે આપવો?",
    meetings: "મીટિંગ્સ",
    meetings_title: "સોસાયટી મીટિંગ્સ",
    meetings_desc: "કોમ્યુનિટી મીટિંગ્સનું આયોજન",
    meeting_confirm: "હાજરીની પુષ્ટિ કરો",
    meeting_archive: "આર્કાઇવ સેન્ટર",
    audit_title: "એક્ટિવિટી ઓડિટ",
    audit_desc: "વહીવટી કાર્યવાહીની દેખરેખ",
    audit_search: "ઓડિટ શોધો...",
    exp_title: "સોસાયટી તિજોરી",
    exp_desc: "ખર્ચ: સફાઈ, સુરક્ષા અને સુવિધાઓ",
    exp_log_new: "નવો ખર્ચ ઉમેરો",
    exp_category: "શ્રેણીઓ",
    total_exp: "કુલ ખર્ચ",
    active_records: "સક્રિય રેકોર્ડ્સ",
    awaiting_appr: "મંજૂરીની રાહ જોવાઈ રહી છે",
    logout: "સાઇન આઉટ",
    office_hours: "ઓફિસ સમય",
    helpline: "હેલ્પલાઇન",
    infrastructure: "ઈન્ફ્રાસ્ટ્રક્ચર",
    system_health: "સિસ્ટમ હેલ્થ",
    revenue: "આવક",
    broadcasts: "સોસાયટી પ્રસારણ",
    launchpad: "લોન્ચપેડ",
    sos: "એસઓએસ",
    bills: "બિલ",
    profile: "પ્રોફાઇલ",
    facilities: "સુવિધાઓ",
    helpdesk: "હેલ્પડેસ્ક",
    book_now: "બુક કરો",
    raise_complaint: "ફરિયાદ કરો",
    complaint_title: "ફરિયાદનું શીર્ષક",
    complaint_desc: "સમસ્યા સમજાવો",
    status_resolved: "ઉકેલાઈ ગયું",
    status_in_progress: "ચાલુ છે"
  },
  hi: {
    greeting_morning: "સુપ્રભાત",
    greeting_afternoon: "શુભ બપોર",
    greeting_evening: "શુભ સાંજ",
    greeting_night: "શુભ રાત્રિ",
    dashboard: "કમાન્ડ સેન્ટર",
    maintenance: "મેન્ટેનન્સ લેબ",
    emergency: "ઇમરજન્સી ડેસ્ક",
    visitors: "વિઝિટર એક્સેસ",
    assets: "રહેણાંક સંપત્તિ",
    treasury: "તિજોરી વિશ્લેષણ",
    audit: "ઓડિટ ટ્રેઇલ",
    funds: "કોમ્યુનિટી ફંડ્સ",
    notices: "બ્રોડકાસ્ટ્સ",
    location: "એટલાસ અને બિલ્ડરો",
    leadership: "નેવતૃત્વ",
    residents: "રહેવાસીઓ",
    status_active: "સક્રિય",
    quick_pay: "ઝડપી ચુકવણી",
    day_shift: "ડે શિફ્ટ",
    night_shift: "નાઇટ શિફ્ટ",
    saurashtra: "सौराष्ट्र",
    residency_portal: "रेजीडेंसी पोर्टल",
    welcome: "સ્વાગત છે",
    back: "પાછા",
    emergency_contacts: "आपातकालीन संपर्क",
    residential_infra: "आवासीय बुनियादी ढांचा",
    finance_hub: "वित्त केंद्र",
    society_bulletin: "सोसायटी बुलेटिन",
    special_funds: "विशेष निधि और कार्यक्रम",
    meet_committee: "हमारी समिति से मिलें",
    site_plan: "साइट प्लान",
    total_units: "कुल इकाइयाँ",
    search_wing: "Search wing (A-1 થી A-24)...",
    view_wing_mgmt: "विंग प्रबंधन देखें",
    pay_now: "ચુકવણી કરો",
    receipt: "રસીદ",
    export: "નિકાસ",
    status_paid: "ચૂકવેલ",
    status_pending: "બાકી",
    status_overdue: "બાકી સમય વીતી ગયો",
    unit: "ઇકાઈ",
    amount: "રકમ",
    actions: "કાર્રવાई",
    profession_engineer: "सॉफ्टवेयर इंजीनियर",
    profession_business: "कपड़ा व्यवसाय",
    profession_merchant: "हीरा व्यापारी",
    profession_teacher: "शिक्षक",
    profession_doctor: "डॉक्टर",
    profession_ca: "चાર્ટર્ડ Accountant",
    profession_govt: "सरकारी अधिकारी",
    profession_retired: "सेवानिवृत्त",
    profession_homemaker: "गृहिणी",
    relation_hof: "परिवार के मुखिया",
    relation_spouse: "जीवनसाथी",
    relation_child: "बच्चा",
    relation_parent: "माता-पिता",
    relation_other: "अन्य",
    visitor_name: "आगंतुक का नाम",
    visitor_phone: "आगंतुक का फ़ोन",
    visitor_purpose: "यात्रा का उद्देश्य",
    visitor_validity: "पास की वैधता",
    visitor_generate: "एक्सेस पास जेनरेट करें",
    visitor_auth: "अधिकृत प्रवेश",
    visitor_share: "पास साझा करें",
    visitor_download: "डाउनलोड करें",
    wing_committee: "વિંગ સમિતિના સભ્યો",
    floor_map: "फ्लोर ऑक्यूपेंसी मैप",
    president: "अध्यक्ष",
    vp: "उपाध्यक्ष",
    treasurer: "कोषाध्यक्ष",
    secretary: "सचिव",
    fund_starts: "શરૂઆત",
    fund_collected: "એકત્રિત",
    fund_target: "લક્ષ્યાંક",
    fund_contribute: "ફાળો આપો",
    fund_how: "ફાળો કેવી રીતે આપવો?",
    meetings: "बैठकें",
    meetings_title: "सोसायटी बैठकें",
    meetings_desc: "सामुदायिक बैठकों का आयोजन",
    meeting_confirm: "उपस्थिति की पुष्टि करें",
    meeting_archive: "पुरालेख केंद्र",
    audit_title: "गतिविधि ऑडिट",
    audit_desc: "પ્રશાસનિક કાર્યવાહીની દેખરેખ",
    audit_search: "ઓડિટ શોધો...",
    exp_title: "સોસાયટી તિજોરી",
    exp_desc: "ખર્ચ: સફાઈ, સુરક્ષા અને સુવિધાઓ",
    exp_log_new: "નવો ખર્ચ ઉમેરો",
    exp_category: "શ્રેણીઓ",
    total_exp: "कुल व्यय",
    active_records: "સક્રિય રેકોર્ડ્સ",
    awaiting_appr: "મંજૂરીની રાહ જોવાઈ રહી છે",
    logout: "સાઇન આઉટ",
    office_hours: "કાર્યાલय સમય",
    helpline: "હેલ્પલાઇન",
    infrastructure: "ઈન્ફ્રાસ્ટ્રક્ચર",
    system_health: "સિસ્ટમ હેલ્થ",
    revenue: "રાજસ્વ",
    broadcasts: "સોસાયટી પ્રસારણ",
    launchpad: "લોન્ચપેડ",
    sos: "એસઓએસ",
    bills: "બિલ",
    profile: "પ્રોફાઇલ",
    facilities: "સુવિધાઓ",
    helpdesk: "હેલ્પડેસ્ક",
    book_now: "બુક કરો",
    raise_complaint: "शिकायत दर्ज करें",
    complaint_title: "शिकायत का शीर्षक",
    complaint_desc: "સમસ્યા સમજાવો",
    status_resolved: "समाधान हो गया",
    status_in_progress: "પ્રગતિમાં"
  }
};

export const BUILDER_INFO: Builder = {
  name: "Saurashtra Developers Group",
  founded: "1998",
  projects: ["Saurashtra Residency", "Vibrant Heights", "Patel Enclave", "Diamond Hub"],
  vision: "To create sustainable, premium living spaces that empower families in the heart of Gujarat.",
  logo: "https://api.dicebear.com/7.x/initials/svg?seed=SDG&backgroundColor=2563eb",
  phone: "+91 261 222 3333",
  email: "contact@saurashtradevelopers.com"
};

export const BUILDINGS: Building[] = Array.from({ length: 24 }, (_, i) => {
  const name = `A-${i + 1}`;
  const type = i < 6 ? FlatType.BHK1 : FlatType.BHK2;
  return {
    id: `bld-${name}`,
    name: name,
    type: type,
    totalFloors: 5,
    flatsPerFloor: 4,
    hasLift: true,
    parkingSpots: 1,
    flats: [], 
    wingCommittee: {
      president: { id: '', name: 'Unassigned', position: 'President', phone: '', email: '', imageUrl: '' },
      vicePresident: { id: '', name: 'Unassigned', position: 'VP', phone: '', email: '', imageUrl: '' },
      treasurer: { id: '', name: 'Unassigned', position: 'Treasurer', phone: '', email: '', imageUrl: '' }
    }
  };
});

export const UTILITY_SUMMARY = BUILDINGS.map((b, i) => {
  return {
    buildingId: b.id,
    buildingName: b.name,
    liftBill: 0,
    commonBill: 0,
    sharedWaterBill: 0,
    sharedWith: i % 2 === 0 && i + 1 < 24 ? `A-${i + 2}` : (i > 0 ? `A-${i}` : '')
  };
});

export const EXPENSE_CATEGORIES = [
  { id: 'GARBAGE', label: 'Garbage Collection', color: '#10b981', icon: 'Trash' },
  { id: 'BUILDING_CLEANING', label: 'Pochha & Safai', color: '#3b82f6', icon: 'Brush' },
  { id: 'SECURITY', label: 'Gate Security', color: '#f59e0b', icon: 'ShieldCheck' }
];

export const COMMITTEE: CommitteeMember[] = [
  { id: '1', name: 'Rajesh Patel', position: 'president', phone: '+91 98765 43210', email: 'rajesh.p@residency.com', imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh' },
  { id: '2', name: 'Suresh Vaghani', position: 'secretary', phone: '+91 98765 43211', email: 'suresh.v@residency.com', imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Suresh' },
  { id: '3', name: 'Manoj Goti', position: 'treasurer', phone: '+91 98765 43212', email: 'manoj.g@residency.com', imageUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Manoj' },
];

export const NOTICES: Notice[] = [];
export const MAINTENANCE_SAMPLES: MaintenanceRecord[] = [];
export const FUNDS: FundRecord[] = [];
